/* Content is based on the supplied Li et al. review. All generated diagrams are
   explanatory schematics, not microscopy images or measured experimental data. */
const source = {
  review: {short: 'Li et al., 2025 · supplied review', url: 'https://doi.org/10.1016/j.cclet.2024.110072'},
  lang: {short: 'Lang et al., 2019 · review ref. 49', url: 'https://doi.org/10.1038/s41467-019-11804-7'},
  qin: {short: 'Qin et al., 2021 · review ref. 14', url: 'https://doi.org/10.1021/acsami.1c11563'},
  deng: {short: 'Deng et al., 2022 · review ref. 75', url: 'https://doi.org/10.1002/adhm.202200115'},
  wang: {short: 'Wang et al., 2020 · review ref. 85', url: 'https://doi.org/10.1021/acs.nanolett.0c01371'},
  correction: {short: 'Wang et al., 2025 · correction', url: 'https://doi.org/10.1021/acs.nanolett.5c03683'}
};
const colors = {green:'#32685b', light:'#b8d4c6', core:'#e8a779', pale:'#f3dac6', ink:'#173e35', blue:'#7296ae'};
const svg = (label, body, viewBox='0 0 760 450') => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" role="img" aria-label="${label}"><title>${label}</title><defs><marker id="arrow-${label.replace(/\W/g,'')}" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0 0L10 5L0 10" fill="#32685b"/></marker></defs>${body}</svg>`;
const line = (x1,y1,x2,y2,color=colors.green,dash='') => `<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="${color}" stroke-width="3" ${dash?`stroke-dasharray="${dash}"`:''}/>`;
const text = (x,y,s,size=23,anchor='middle',color=colors.ink) => `<text x="${x}" y="${y}" text-anchor="${anchor}" fill="${color}" font-family="Lato, sans-serif" font-size="${size}">${s}</text>`;
const dot = (x,y,r=5,c=colors.core) => `<circle cx="${x}" cy="${y}" r="${r}" fill="${c}"/>`;
function micelle(x,y,r=44,drugs=true){
  let b=`<circle cx="${x}" cy="${y}" r="${r*1.34}" fill="#dfece3" opacity=".55"/><circle cx="${x}" cy="${y}" r="${r*.73}" fill="${colors.pale}" stroke="${colors.core}" stroke-width="2"/>`;
  for(let i=0;i<22;i++){const a=i*Math.PI*2/22, q=(rr,off=0)=>[x+Math.cos(a+off)*rr,y+Math.sin(a+off)*rr];const p=q(r*.7),p1=q(r*.95,.1),p2=q(r*1.15,-.06),p3=q(r*1.3,.04);b+=`<path d="M${p} Q${p1} ${p2} T${p3}" fill="none" stroke="${colors.green}" stroke-width="2.5" stroke-linecap="round"/>`;b+=dot(...p3,2.6,colors.green);}
  if(drugs){for(const [dx,dy] of [[-12,-10],[11,-6],[0,13],[-19,10]])b+=dot(x+dx*r/44,y+dy*r/44,4.5*r/44,'#c97442');}
  return b;
}
function network(x=70,y=60,w=600,h=330,junctions=false){
  let b=`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="24" fill="#eaf0e5"/>`;
  for(let row=0;row<4;row++){const yy=y+35+row*(h-70)/3;b+=`<path d="M${x+18} ${yy} C${x+w*.2} ${yy-42},${x+w*.3} ${yy+40},${x+w*.46} ${yy} S${x+w*.75} ${yy-35},${x+w-18} ${yy}" fill="none" stroke="${colors.green}" stroke-width="3.5"/>`;}
  for(let col=0;col<5;col++){const xx=x+40+col*(w-80)/4;b+=`<path d="M${xx} ${y+18} C${xx-30} ${y+h*.3},${xx+35} ${y+h*.43},${xx} ${y+h*.55} S${xx-20} ${y+h*.8},${xx} ${y+h-18}" fill="none" stroke="${colors.green}" stroke-width="3.5"/>`;}
  if(junctions){for(const [dx,dy] of [[.27,.28],[.7,.25],[.42,.65],[.78,.7]])b+=micelle(x+w*dx,y+h*dy,24);}
  return b;
}
const diagrams = {
  cover:()=>svg('Micelles incorporated into a water-rich polymer network',`<circle cx="380" cy="236" r="207" fill="#e4eddd"/><circle cx="380" cy="236" r="177" fill="none" stroke="#b9cdb7" stroke-dasharray="3 9"/>${network(145,88,475,318,true)}${micelle(602,112,64)}${line(565,165,508,221,colors.core,'6 6')}${text(379,440,'A nanoscale carrier. A tissue-scale scaffold.',20)}`),
  pairing:()=>svg('Micelles carry hydrophobic cargo; hydrogels create a local depot',`${micelle(180,180,75)}${text(180,325,'MICELLE',22)}${text(180,359,'Carries water-shy drugs',21)}${text(367,193,'+',42)}${network(445,81,260,230,false)}${text(575,354,'HYDROGEL',22)}${text(575,388,'Retains a local reservoir',21)}`),
  anatomy:()=>svg('Hydrophobic core with drug surrounded by hydrated hydrophilic polymer chains',`${micelle(300,220,104)}${line(332,211,515,136,colors.core)}${text(532,132,'Hydrophobic core',25,'start')}${text(532,166,'Drug-rich compartment',18,'start')}${line(353,112,515,48)}${text(532,48,'Hydrophilic corona',24,'start')}${line(206,309,90,377)}${text(75,406,'Hydrated chains face water',21,'start')}${dot(294,216,8,'#c97442')}${text(468,362,'●  Hydrophobic drug',22,'start','#c97442')}`),
  gel:()=>svg('Water-rich polymer network; mesh size is the spacing between network chains',`${network(74,65,587,308,false)}${dot(237,100,6)}${dot(237,189,6)}${line(238,111,238,177,colors.core)}${text(272,146,'ξ',32,'start','#c97442')}${line(563,144,708,102)}${text(720,100,'Chain',21)}${line(120,233,36,273,colors.blue)}${text(380,417,'Water occupies the spaces between connected chains.',22)}${dot(388,124,6,colors.blue)}${dot(477,252,6,colors.blue)}${dot(193,315,6,colors.blue)}${dot(580,309,6,colors.blue)}`),
  routes:()=>svg('Three routes: embedded micelles, micelle crosslinkers, and micelles forming their own gel',`${network(10,80,215,210,false)}${micelle(70,170,23)}${micelle(154,228,23)}${text(115,332,'01 · EMBED',22)}${text(115,369,'Guests in a network',19)}${network(270,80,215,210,true)}${text(377,332,'02 · CONNECT',22)}${text(377,369,'Network junctions',19)}${micelle(568,117,23)}${micelle(656,124,23)}${micelle(568,214,23)}${micelle(660,227,23)}${line(568,150,568,180)}${line(590,136,631,136)}${line(590,220,632,226)}${line(660,154,660,194)}${text(626,332,'03 · SELF-ASSEMBLE',22)}${text(626,369,'The gel-forming material',19)}`),
  embed:()=>svg('Preformed micelles mixed into a separately crosslinked polymer hydrogel',`${micelle(131,182,44)}${text(130,291,'Preformed micelles',21)}${text(288,188,'+',38)}<path d="M345 139Q390 90 422 159T503 146M347 216Q390 166 420 223T504 208" fill="none" stroke="#32685b" stroke-width="4"/>${text(426,290,'Gel precursors',21)}${text(553,186,'→',38)}${network(602,103,145,166,false)}${micelle(650,167,17)}${micelle(705,220,17)}${text(650,291,'Crosslink',21)}${text(375,394,'Micelles are retained by the surrounding matrix.',23)}`),
  crosslink:()=>svg('Functionalized micelles act as junctions linking multiple polymer chains',`${network(70,65,600,308,true)}${line(489,139,691,46,colors.core)}${text(698,35,'Reactive groups',20)}${dot(489,139,6,colors.core)}${dot(476,156,6,colors.core)}${text(369,421,'A carrier becomes part of the load-bearing network.',23)}`),
  selfgel:()=>svg('Micellar solution becomes a connected gel under a formulation-specific trigger',`${micelle(95,123,24,false)}${micelle(194,194,24,false)}${micelle(104,285,24,false)}${micelle(256,96,24,false)}${text(170,383,'Flowing solution',23)}${text(379,156,'→',40)}${text(378,204,'Temperature',20)}${text(378,234,'or salt',20)}${line(513,115,628,130)}${line(513,115,511,260)}${line(628,130,656,269)}${line(511,260,656,269)}${line(511,260,628,130)}${micelle(513,115,29,false)}${micelle(628,130,29,false)}${micelle(511,260,29,false)}${micelle(656,269,29,false)}${text(587,383,'Connected micellar gel',23)}`),
  bonds:()=>svg('Reversible interactions can break and reform; dynamic covalent bonds are one example',`${micelle(131,188,39,false)}${micelle(587,188,39,false)}<path d="M190 188Q245 122 301 188" stroke="#32685b" stroke-width="4" fill="none"/><path d="M416 188Q471 248 527 188" stroke="#32685b" stroke-width="4" fill="none"/>${dot(301,188,7)}${dot(416,188,7)}${line(310,188,409,188,colors.core,'5 7')}${text(359,124,'Break ⇄ Re-form',27)}${text(359,283,'Dynamic junction',24)}<rect x="104" y="337" width="550" height="65" rx="14" fill="#e9eedf"/>${text(380,378,'R–CHO + H₂N–R′ ⇄ R–CH=N–R′ + H₂O',24)}`),
  mechanics:()=>svg('Reversible junctions open during deformation and reform after unloading',`${network(15,101,220,190,true)}${text(127,351,'AT REST',23)}${text(274,195,'→',35)}<rect x="327" y="130" width="370" height="128" rx="22" fill="#eaf0e5"/><path d="M339 169Q410 140 486 169T684 169M339 222Q415 191 486 222T684 222" stroke="#32685b" fill="none" stroke-width="4"/>${micelle(423,167,23)}${micelle(582,225,23)}${line(430,205,582,190,colors.core,'5 8')}${text(506,351,'UNDER STRAIN',23)}${text(381,419,'Junction rearrangement can dissipate energy.',23)}`),
  stimuli:()=>svg('A selected stimulus changes the material chemistry or structure and alters drug release',`<rect x="32" y="131" width="181" height="161" rx="18" fill="#e9eedf"/>${text(122,185,'Stimulus',27)}${text(122,229,'pH · ROS · heat',21)}${text(255,221,'→',37)}<rect x="299" y="131" width="179" height="161" rx="18" fill="#f3dac6"/>${text(389,184,'Material',27)}${text(389,218,'Bonds / core',21)}${text(389,248,'change',21)}${text(520,221,'→',37)}${micelle(641,210,45)}${dot(721,191,7,'#c97442')}${dot(734,237,7,'#c97442')}${text(641,325,'Release changes',23)}${text(380,418,'The response must be engineered into the polymer.',23)}`),
  tumor:()=>svg('Gemcitabine in the aqueous gel and d-1-methyltryptophan in micelles create separate release compartments',`${network(51,52,626,255,true)}${dot(185,227,7,colors.blue)}${dot(397,133,7,colors.blue)}${dot(490,248,7,colors.blue)}${line(397,133,464,341,colors.blue)}${text(474,364,'GEM in aqueous gel',22,'start')}${line(220,123,178,341,colors.core)}${text(90,399,'d-1MT in micelle cores',22,'start')}`),
  tissue:()=>svg('Bone and nerve scaffolds require different mechanics and biological functions',`<rect x="28" y="52" width="317" height="315" rx="22" fill="#e8eddf"/><path d="M134 96Q107 74 95 94Q74 129 114 150L130 270Q101 292 119 311Q140 333 166 309Q196 329 207 307Q219 287 182 268L164 151Q206 133 194 103Q181 78 157 103Z" fill="#f3dac6" stroke="#32685b" stroke-width="3"/>${micelle(233,227,30)}${text(188,345,'BONE',24)}<rect x="397" y="52" width="334" height="315" rx="22" fill="#e8eddf"/><path d="M432 202C480 161 518 229 556 189S654 214 698 179" fill="none" stroke="#32685b" stroke-width="8"/><path d="M519 198L491 126M584 187L623 118M633 199L677 264" stroke="#32685b" stroke-width="4"/>${micelle(558,255,26)}${text(565,345,'NERVE',24)}${text(188,420,'Support + osteogenic cues',22)}${text(565,420,'Softness + guidance + cargo',22)}`),
  evidence:()=>svg('Progression from material measurements to cells, animals, and human clinical evidence',`<path d="M79 314H690" fill="none" stroke="#b8d4c6" stroke-width="4"/>${[119,283,447,611].map((x,i)=>`${dot(x,314,17,i<3?colors.green:colors.core)}${text(x,247,['Material','Cells','Animals','Humans'][i],26)}${text(x,376,['Mechanism','Bioactivity','In vivo effects','Clinical benefit'][i],20)}`).join('')}${text(379,116,'A promising mechanism is an early step.',32)}${text(379,165,'Each stage answers a different question.',23)}`)
};
const card=(n,title,body)=>`<div class="concept-card"><span class="card-index">${n}</span><h3>${title}</h3><p>${body}</p></div>`;
const bullets=(items)=>`<ul class="scientific-list">${items.map(([a,b])=>`<li><strong>${a}</strong><span>${b}</span></li>`).join('')}</ul>`;
const figure=(d,caption)=>`<figure class="diagram">${d}<figcaption>${caption}</figcaption></figure>`;
const cols=(copy,visual)=>`<div class="slide-columns"><div class="slide-copy">${copy}</div>${visual}</div>`;
const chapters=['Foundations','Design routes','Material behavior','Biomedical applications','Think like a researcher'];
const slides=[
  {
    chapter:0, title:'Small carriers.<br><span class="accent">Big possibilities.</span>', nav:'The big idea', layout:'cover',
    body:`<div class="cover-columns"><div><div class="paper-tag"><span></span> A GUIDED SCIENTIFIC LESSON</div><h1>Small carriers.<br><span class="accent">Big possibilities.</span></h1><p class="cover-subtitle">Understanding polymeric<br>micelle–hydrogel composites</p><div class="cover-meta"><span>20 slides</span><i></i><span>Diagrams & explanations</span></div><div class="paper-credit">Based on Hongyi Li et al.<br><em>Chinese Chemical Letters</em> 36 (2025), 110072</div></div>${figure(diagrams.cover(),'Conceptual schematic · not to scale')}</div>`,
    takeaway:'How nanoscale drug carriers and water-rich networks work together.', refs:['review'],
    notes:'This lesson explains the supplied review, rather than presenting a new experiment. It assumes basic familiarity with polymers and builds the nanomaterials concepts from the beginning. The central question is how the way a micelle joins a hydrogel changes mechanics, cargo retention, and biomedical function. The article was available online in 2024 and appeared in the 2025 journal volume. All original diagrams are teaching schematics, not measured structures.'
  },
  {
    chapter:0,title:'Two materials solve different problems.',nav:'Why combine them?',
    body:cols(bullets([['The micelle','A hydrophobic core carries drugs that disperse poorly in water.'],['The hydrogel','A water-rich network forms a local depot or scaffold.'],['The composite','Couples cargo handling with retention and material function.']]),figure(diagrams.pairing(),'Two roles, combined in one material.')),
    takeaway:'Micelles handle the cargo; the gel provides the surrounding architecture.',refs:['review'],
    notes:'Many biomedical hydrogels contain mostly water. That makes them useful as tissue-like environments, but poorly suited to uniformly distributing very hydrophobic drugs without a carrier. An amphiphilic micelle provides a drug-compatible compartment. The gel adds a larger-scale structure that can retain the formulation near an application site. This combination can be useful, but performance and compatibility depend on the actual chemistry. It is not a universal guarantee of better mechanics or safety.'
  },
  {
    chapter:0,title:'A micelle has a core and a corona.',nav:'Inside a micelle',
    body:cols(`<p class="lead">An amphiphilic polymer has both water-loving and water-avoiding segments.</p>${bullets([['In water','Hydrophobic segments associate inside; hydrated segments face out.'],['With cargo','Compatible hydrophobic drugs partition into the core.'],['A stability constraint','Dilution and changing conditions can disrupt the assembly.']])}`,figure(diagrams.anatomy(),'A typical core–corona micelle · not all micelles are spherical.')),
    takeaway:'Self-assembly creates a drug-compatible compartment within water.',refs:['review'],
    notes:'Amphiphilic means that different parts of the same molecule have different affinities for water. The outer hydrated polymer region is often called the corona. The core is enriched in hydrophobic segments; it is not necessarily an empty cavity. Cargo loading depends on drug–polymer compatibility, polymer composition, and formulation. A critical micelle concentration describes a concentration threshold for micellization under specified conditions. Crossing this threshold does not by itself fully predict the stability of kinetically trapped polymeric micelles. The diagram simplifies shape, size, and molecular packing.'
  },
  {
    chapter:0,title:'A hydrogel is a connected, hydrated network.',nav:'Inside a hydrogel',
    body:cols(bullets([['Polymer chains','Physical or chemical junctions connect the chains.'],['Water-filled spaces','Transport depends on the network and the molecule moving through it.'],['Mesh size, ξ','A useful idea for the spacing between network chains.']]),figure(diagrams.gel(),'ξ = mesh size · schematic network, not a measured pore structure.')),
    takeaway:'The network must support the application while allowing useful transport.',refs:['review'],
    notes:'A hydrogel is a three-dimensional polymer network that holds a large amount of water. The connections prevent simple dissolution on the relevant timescale. Mesh size is a molecular-scale network concept and should not be confused with large pores seen in a dried microscopy sample. Stiffness, swelling, degradation, and transport are linked to the polymer chemistry and network structure. Micelles may be physically trapped, interact with the chains, or be actual junctions. These possibilities lead to the review’s three main design routes.'
  },
  {
    chapter:1,title:'The key choice: how does the micelle join?',nav:'Three design routes',
    body:`<div class="wide-figure">${figure(diagrams.routes(),'Classification follows the micelle’s structural role in the final material.')}</div>`,
    takeaway:'Embedded guest, network junction, or gel-forming building block.',refs:['review'],
    notes:'The review groups fabrication approaches into three main routes. In the first, the surrounding hydrogel forms in a preassembled micellar suspension. In the second, micelles participate as network crosslinkers. In the third, micelles or their constituent amphiphilic polymers form the gel themselves under appropriate conditions. Actual formulations can contain more than one type of interaction; the categories are a design map. A useful diagnostic question is whether the polymer matrix could form its network without the micelles.'
  },
  {
    chapter:1,title:'Route 01 / Embed preformed micelles.',nav:'01 · Embed',
    body:cols(`<div class="route-badge">MICELLES AS GUESTS</div>${bullets([['Build','Load micelles, mix with precursors, then form the gel.'],['Gain','Flexibility to incorporate different micelle functions.'],['Tradeoff','Weak retention can allow micelles to escape.']])}`,figure(diagrams.embed(),'The surrounding polymer forms the network independently.')),
    takeaway:'Simple incorporation requires careful control of retention.',refs:['review'],
    notes:'A standard route is to add already prepared micelles to a gel-forming solution, followed by crosslinking or a change in formulation conditions. The review also describes soaking a previously dried hydrogel in a micellar solution. This route separates carrier design from matrix fabrication and can simplify mixing different functions. It does not guarantee uniform distribution or permanent trapping: mesh size, swelling, micelle size, and matrix interactions all matter. Verify retention experimentally rather than inferring it from the presence of a gel.'
  },
  {
    chapter:1,title:'Route 02 / Make micelles the junctions.',nav:'02 · Connect',
    body:cols(`<div class="route-badge">MICELLES AS CROSSLINKERS</div>${bullets([['Build','Connect functionalized micelles to polymer chains.'],['Gain','Cargo carriers also shape the network’s mechanics.'],['Tradeoff','Changing micelle content couples loading, mechanics, and release.']])}`,figure(diagrams.crosslink(),'Micelle surface groups connect to the surrounding matrix.')),
    takeaway:'A micelle can carry a drug and help hold the gel together.',refs:['review'],
    notes:'Here the micelle is structurally involved in network formation. Reactive groups on a micelle or reversible interactions between micelles and polymer chains make it a junction that links multiple chains. The review includes aldehyde-modified Pluronic F127 micelles and polymerization-induced self-assembly strategies for making tailored micellar crosslinkers. Changing the concentration, size, or chemistry of these micelles may alter crosslink density, energy dissipation, and cargo release at the same time. Higher micelle content is not automatically better, and a crosslinker need not rely only on covalent bonds.'
  },
  {
    chapter:1,title:'Route 03 / Let the micelles form the gel.',nav:'03 · Self-assemble',
    body:cols(`<div class="route-badge">MICELLES AS BUILDING BLOCKS</div>${bullets([['Build','A suitable amphiphilic polymer forms a connected micellar network.'],['Trigger','Temperature, concentration, salt, or solvent conditions.'],['Tradeoff','Formulation-specific gelation and possible mechanical weakness.']])}`,figure(diagrams.selfgel(),'A sol–gel transition requires connectivity, not merely micelle formation.')),
    takeaway:'No separate matrix is required, but the polymer must be designed for gelation.',refs:['review','lang'],
    notes:'Micellization and gelation are different transitions. Discrete micelles can exist in a flowing solution; a gel requires a sufficiently connected or crowded structure. Some temperature-sensitive block copolymers undergo a sol–gel transition, while other systems use salt or solvent changes. Lang et al. showed that initial polymer solution concentration before rapid injection into water could select micelles, microgels, or hydrogels for their ABA copolymers. That is a specific solvent-driven process and should not be treated as a general temperature-gelation rule. Thermal triggers must also be compatible with the cargo.'
  },
  {
    chapter:2,title:'Reversible junctions allow repair.',nav:'Dynamic interactions',
    body:cols(bullets([['Physical interactions','Hydrogen bonding, electrostatic attraction, and host–guest binding.'],['Dynamic covalent bonds','Examples include imine and hydrazone connections.'],['Macroscopic behavior','Junction exchange can support self-healing and injectability.']]),figure(diagrams.bonds(),'Example: reversible imine formation; rates depend on chemistry and conditions.')),
    takeaway:'Self-healing requires connections that re-form on a useful timescale.',refs:['review'],
    notes:'The equation shows an aldehyde plus a primary amine forming an imine and water. It is a schematic representation of a reversible reaction, not a synthesis protocol. The review discusses several dynamic covalent bond types as well as reversible physical interactions. Bond identity alone does not guarantee fast self-healing: reaction rate, chain mobility, contact between damaged surfaces, and the surrounding environment matter. Shear thinning, injectability, and self-healing are related possibilities but distinct properties that should be measured separately.'
  },
  {
    chapter:2,title:'Toughness comes from managing energy.',nav:'Mechanics & toughness',
    body:cols(`<p class="lead">A network can resist a crack by redistributing stress and dissipating energy.</p>${bullets([['Under deformation','Reversible junctions can rearrange or temporarily separate.'],['On recovery','Mobile chains and junctions can reconnect.'],['Measure separately','Stiffness, stretchability, toughness, and fatigue resistance.']])}`,figure(diagrams.mechanics(),'Proposed mechanism illustrated schematically; no experimental stress data.')),
    takeaway:'A stiffer gel is not necessarily a tougher or more fatigue-resistant gel.',refs:['review'],
    notes:'Stiffness describes resistance to small deformation; toughness describes energy required to cause fracture. Fatigue resistance concerns damage during repeated loading. The review highlights micellar systems in which movable junctions and chain slippage dissipate crack energy. Mechanisms and outcomes differ across systems: increasing permanent crosslinks can stiffen a gel while limiting extensibility, whereas reversible interactions can introduce time-dependent behavior. A persuasive mechanical claim requires relevant stress–strain, fracture, recovery, and cyclic-loading measurements, rather than a single photograph of a stretched sample.'
  },
  {
    chapter:2,title:'Drug release can involve two transport steps.',nav:'Explore release',
    body:`<div class="release-layout"><div class="release-controls"><div class="route-badge">INTERACTIVE TEACHING MODEL</div><h3>Core → gel → surroundings</h3><p>Change how quickly cargo leaves the micelle. The gel adds a second transport step.</p><label for="release-rate">Micelle release half-time <output id="release-value">3.0</output></label><input id="release-rate" type="range" min="1" max="8" value="3" step="0.5"><div class="range-labels"><span>Faster</span><span>Slower</span></div><p class="model-fixed">Gel transport half-time = 2 relative units</p><p class="model-note">Illustrative first-order model. Arbitrary relative time; no fitted or measured data.</p></div><figure class="release-figure"><svg id="release-chart" viewBox="0 0 760 430" role="img" aria-label="Illustrative cumulative release from a micelle alone versus a sequential micelle and gel system"></svg><figcaption>Comparison isolates a second transport step; actual gels may behave differently.</figcaption></figure></div>`,
    takeaway:'Cargo partitioning, matrix transport, degradation, and micelle escape all matter.',refs:['review'],
    notes:'This illustration assumes all cargo begins in micelles, moves into the gel with a constant first-order rate kₘ, then exits the gel with rate k𝗀. It assumes irreversible transfer, sink conditions, no initial free cargo, and no carrier escape or degradation. For unequal rates, cumulative external release is F(t) = 1 − [k𝗀 exp(−kₘt) − kₘ exp(−k𝗀t)] / (k𝗀 − kₘ). For equal rates it is 1 − exp(−kt)(1 + kt). Rates are ln(2) divided by half-time. The control changes kₘ while the gel half-time remains 2 arbitrary relative units. This is an original pedagogical model, not an equation fitted in the paper or a prediction of clinical release. Real systems can involve burst release, diffusion, binding, erosion, cargo exchange, or escaping micelles.'
  },
  {
    chapter:2,title:'A stimulus must connect to a mechanism.',nav:'Stimuli-responsive design',
    body:cols(bullets([['pH changes','Can alter ionization or the stability of chosen dynamic bonds.'],['Redox / ROS','Can act on specially designed sensitive groups.'],['Temperature / force','Can change assembly, network state, or micelle structure.']]),figure(diagrams.stimuli(),'Stimulus → material change → altered transport or release.')),
    takeaway:'“Responsive” describes a designed chemical pathway, not a universal property.',refs:['review'],
    notes:'ROS means reactive oxygen species. A material responds only when it contains chemistry or a structure sensitive to the selected stimulus. A bond may cleave, a hydrophobic core may change, or network connectivity may shift. Different mechanisms can accelerate or slow release, so the direction of the effect must be tested. The review includes pH, redox, ROS, temperature, and force-responsive examples. To assess a design, ask whether the stimulus level at the target site is sufficient, whether it also exists elsewhere, and how the response compares with an otherwise equivalent control.'
  },
  {
    chapter:3,title:'Tumor therapy: separate cargo, stage delivery.',nav:'Local tumor therapy',
    body:cols(`<span class="evidence-tag">PRECLINICAL EXAMPLE</span>${bullets([['Two compartments','Hydrophilic gemcitabine (GEM) in the gel; hydrophobic d-1MT in micelle cores.'],['One local depot','Micelles participate in thiol–ene network formation.'],['Design purpose','Sequential chemotherapy and immune modulation.']])}`,figure(diagrams.tumor(),'Qin et al. · breast-tumor model; schematic cargo allocation.')),
    takeaway:'Compartment design can tune the timing of combination delivery.',refs:['review','qin'],
    notes:'Qin et al. placed gemcitabine in the aqueous hydrogel network and the hydrophobic IDO inhibitor d-1-methyltryptophan in F127 micelles. Thiolated chondroitin sulfate and methacrylated F127 micelles formed a network by thiol–ene chemistry. The study evaluated localized chemo-immunotherapy in a 4T1 tumor-bearing mouse model. The design lesson is that two cargo compartments offer different transport pathways and can support sequential release. It does not mean that any pair of drugs will release in a clinically useful order, or that a local depot automatically targets every tumor cell. These are preclinical findings, not demonstrated human treatment benefits.'
  },
  {
    chapter:3,title:'Tissue repair starts with the tissue’s needs.',nav:'Bone & nerve scaffolds',
    body:cols(`<div class="tissue-copy"><h3>Bone</h3><p>Combine a scaffold with sustained osteogenic cues. The review describes simvastatin-loaded micelle junctions.</p><h3>Nerve</h3><p>Prioritize suitable softness, transport, and guidance. A conductive micellar gel delivered DHF in a nerve conduit.</p></div><span class="evidence-tag">CELL / ANIMAL RESEARCH</span>`,figure(diagrams.tissue(),'DHF = 7,8-dihydroxyflavone · diagrams do not imply native tissue replacement.')),
    takeaway:'A delivery scaffold should fit the tissue; one formulation cannot fit every task.',refs:['review','deng'],
    notes:'The review’s simvastatin example uses aldehyde-modified maltodextrin micelles anchored by Schiff-base chemistry and reports osteogenic differentiation of MC3T3-E1 cells in vitro. This is not evidence that the gel can replace load-bearing bone. For nerves, Deng et al. used polyaniline-modified carboxymethyl chitosan with aldehyde-modified F127 in an outer chitosan conduit. The DHF-loaded conductive gel was studied in a rat sciatic nerve defect model. A tissue scaffold must also support nutrient transport, compatible degradation, cell behavior, and the mechanical environment. Compare findings within the actual experimental model rather than generalizing to all tissue repair.'
  },
  {
    chapter:3,title:'Wound repair: several functions, one material.',nav:'A wound-healing example',
    body:`<div class="article-layout"><div class="slide-copy"><span class="evidence-tag">FEMI · PRECLINICAL EXAMPLE</span>${bullets([['Micelles','Insulin-loaded aldehyde F127 micelles take part in network formation.'],['Nanosheets','Polylysine-coated MnO₂ adds antibacterial and oxidative-environment functions.'],['Network','Schiff-base connections integrate the components.']])}<p class="correction-note">Read with the <a href="${source.correction.url}" target="_blank" rel="noopener">2025 image correction ↗</a>.</p></div><figure class="article-figure"><img src="assets/femi-figure.png" alt="Review Figure 7: insulin-loaded F127 micelles combine with polylysine-coated manganese dioxide nanosheets to form FEMI hydrogel; schematic wound-healing sequence." width="1094" height="723"><figcaption>Figure 7, supplied Li et al. review; reproduced there from Wang et al., © 2020 ACS. Cropped from page 6.</figcaption></figure></div>`,
    takeaway:'Multifunctionality is useful only when each component’s role is verified.',refs:['review','wang','correction'],
    notes:'FEMI combines insulin-loaded aldehyde F127 micelles with ε-polylysine-coated manganese dioxide nanosheets. The micelles participate in Schiff-base network formation. The paper describes antimicrobial activity and an effect on the oxidative wound environment, and studies an infected diabetic wound model. The displayed image is the review’s design schematic, not an outcome photograph. A September 2025 correction replaced duplicated or mislabeled experimental images in the original study’s Figure 3e and 3f; the authors state that their statistical analyses and main conclusions were unchanged. The correction is linked so the evidence can be read in its updated form. The reaction scheme in this extracted figure is illustrative, not a balanced stoichiometric equation.'
  },
  {
    chapter:4,title:'Choose a route by its tradeoffs.',nav:'Compare the routes',
    body:`<table class="comparison-table"><thead><tr><th>Design question</th><th><span>01</span> Embed</th><th><span>02</span> Connect</th><th><span>03</span> Self-assemble</th></tr></thead><tbody><tr><th>Micelle’s role</th><td>Cargo-bearing guest</td><td>Network junction</td><td>Gel building block</td></tr><tr><th>Design appeal</th><td>Modular formulation</td><td>Integrated mechanics<br>and delivery</td><td>Fewer distinct<br>matrix components</td></tr><tr><th>Main constraint</th><td>Carrier escape</td><td>Coupled formulation<br>variables</td><td>Specific gelation<br>conditions</td></tr><tr><th>What to verify</th><td>Retention + distribution</td><td>Network + cargo function</td><td>Gel window + stability</td></tr></tbody></table><p class="table-caption">Qualitative design guide synthesized from the review; no universal ranking.</p>`,
    takeaway:'Match the route to the cargo, delivery site, mechanics, and fabrication needs.',refs:['review'],
    notes:'Start by defining the cargo and application: solubility, desired exposure, injection or placement method, expected mechanical loading, and degradation requirements. Embedding is attractive when carrier and matrix functions should be developed separately, but micelle retention must be demonstrated. Crosslinking integrates the carrier into the structure and can constrain independent adjustment of dose and mechanics. Self-assembly can reduce the number of matrix components but relies on a suitable polymer and gelation window. No route is always safest, toughest, simplest to manufacture, or best for release.'
  },
  {
    chapter:4,title:'Promising research needs a translation path.',nav:'Evidence & open questions',
    body:cols(bullets([['Measure the mechanism','Loading, carrier retention, mechanics, release, and degradation.'],['Test the biology','Relevant controls, tissue compatibility, and useful effects.'],['Resolve translation','Biosafety, breakdown products, reproducibility, and manufacturing.']]),figure(diagrams.evidence(),'The supplied review describes a developing research field.')),
    takeaway:'Material performance and animal results do not establish human clinical benefit.',refs:['review'],
    notes:'The review’s conclusions state that clinical application of the discussed composites remained limited and that degradation, biosafety, and side effects required further investigation. This lesson reports that assessment rather than claiming an exhaustive 2026 clinical or regulatory status. Future directions in the review include biosensors, 3D printing, flexible electronics, and hydrogel-based vaccines. Those are prospects, not demonstrated capabilities of every material. In research design, use free-drug, blank-gel, micelle-only, and appropriate nonresponsive controls to identify which component or mechanism changes the outcome.'
  },
  {
    chapter:4,title:'Check your understanding.',nav:'Three quick checks',
    body:`<div class="quiz-grid">${[
      ['01','A micelle is present, but the matrix gels without it. Which route is this?',['Embed','Connect','Self-assemble'],0,'Embed. The micelle is a guest in an independently formed network.'],
      ['02','A gel has a higher small-strain modulus. What is directly supported?',['Greater stiffness','Greater toughness','Better fatigue resistance'],0,'Greater stiffness. Fracture and cyclic-loading tests answer the other questions.'],
      ['03','A composite improves healing in an animal model. What follows?',['Human benefit is established','The mechanism is universal','Preclinical evidence is promising'],2,'Promising preclinical evidence. Human benefit requires suitable clinical evidence.']
    ].map(([n,q,answers,correct,explanation])=>`<div class="quiz-card"><span class="card-index">${n}</span><h3>${q}</h3><div class="quiz-options">${answers.map((a,i)=>`<button data-answer="${i}" data-correct="${correct}" aria-pressed="false">${a}</button>`).join('')}</div><p class="quiz-feedback" aria-live="polite" hidden>${explanation}</p><p class="print-answer">${explanation}</p></div>`).join('')}</div>`,
    takeaway:'Explain the structure, the mechanism, and the strength of the evidence.',refs:['review'],
    notes:'Try to answer without rereading the earlier slides. First, classify a formulation by the structural role of its micelles, not just by its ingredients. Second, distinguish stiffness from fracture toughness and fatigue performance. Third, match a biological claim to the model that supports it. If you can explain why a micelle–hydrogel composite is useful, identify the three design routes, and discuss a release or mechanics tradeoff, you have captured the review’s main ideas. In the exported PDF, the explanations appear directly under each question.'
  },
  {
    chapter:4,title:'Follow the evidence. Keep the big idea.',nav:'Sources & takeaways',
    body:`<div class="sources-layout"><div class="closing-card"><span class="tiny-label">THREE THINGS TO REMEMBER</span><h3>Structure shapes<br><span class="accent">function.</span></h3><p>01 · Pair a drug-compatible core with a hydrated scaffold.</p><p>02 · Choose how micelles participate in the network.</p><p>03 · Test the mechanism and qualify the evidence.</p></div><div class="source-list"><a href="${source.review.url}" target="_blank" rel="noopener"><b>01 / THE MAIN ARTICLE</b><span>Li et al. (2025). Polymeric micelle-hydrogel composites design for biomedical applications.</span><small>Chinese Chemical Letters 36, 110072 · DOI: 10.1016/j.cclet.2024.110072 ↗</small></a><a href="${source.lang.url}" target="_blank" rel="noopener"><b>02 / SELF-ASSEMBLY</b><span>Lang et al. (2019). Solvent-non-solvent rapid-injection…</span><small>Nature Communications 10, 3855 · DOI: 10.1038/s41467-019-11804-7 ↗</small></a><a href="${source.qin.url}" target="_blank" rel="noopener"><b>03 / LOCAL COMBINATION DELIVERY</b><span>Qin et al. (2021). Injectable micelle-incorporated hydrogels…</span><small>ACS AMI 13, 46270–46281 · DOI: 10.1021/acsami.1c11563 ↗</small></a><a href="${source.deng.url}" target="_blank" rel="noopener"><b>04 / NERVE REPAIR</b><span>Deng et al. (2022). Multifunctional double-layer composite hydrogel conduit…</span><small>Advanced Healthcare Materials 11, 2200115 · DOI: 10.1002/adhm.202200115 ↗</small></a><a href="${source.wang.url}" target="_blank" rel="noopener"><b>05 / WOUND EXAMPLE + CORRECTION</b><span>Wang et al. (2020). Nanoenzyme-reinforced injectable hydrogel…</span><small>Nano Letters 20, 5149–5158 · DOI: 10.1021/acs.nanolett.0c01371 ↗</small></a><a class="correction-source" href="${source.correction.url}" target="_blank" rel="noopener">2025 correction · DOI: 10.1021/acs.nanolett.5c03683 ↗</a></div></div>`,
    takeaway:'The design route connects chemistry, architecture, delivery, and application.',refs:['review'],
    notes:'The supplied PDF is the central teaching source. Primary studies were checked online to verify selected examples and their experimental models. Reference 49 in the review is Lang et al.; reference 14 is Qin et al.; reference 75 is Deng et al.; reference 85 is Wang et al. The wound-study correction was published after the review and is provided as an update. The bone example comes from review reference 69, Yan et al., Biomacromolecules 19 (2018), 4554–4564. Except for the explicitly attributed cropped review Figure 7, all visual diagrams are original conceptual illustrations. The release plot is an original illustrative model; it contains no experimental data. Research checked on October 2, 2026.'
  }
];
window.MICELLE={slides,chapters,source};
